# Targets 'n stuff for SGI only  -  much of this is for compiling
# with -O3, which is experimental and may or may not work.  Oh well.

OPTFLAGS      = -O3
UCODE         = $(LIBSRC:.c=.u)
OPTLIBRARY    = libmpeg_O3.a
EASYMPEG      = easympeg

.c.u:
		$(CC) $(OPTFLAGS) -j $<

$(OPTLIBRARY):	$(UCODE)
		$(AR) $(ARFLAGS) $(OPTLIBRARY) $(UCODE)
optlib:		$(OPTLIBRARY)

opttest:	$(OPTLIBRARY) mpegtest.u ParseArgv.u
		$(CC) $(OPTFLAGS) mpegtest.u ParseArgv.u -o $@ -L. -lmpeg_O3

